/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../components/Header";
import { sanityClient, urlFor } from "../sanity";
import { Post } from "../typings";

interface Props {
  posts: [Post];
}

export default function Home({ posts }: Props) {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Mukhtars Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/beard.png" />
      </Head>

      <Header />

      <div
        className="px-10 py-10 lg:py-0 space-y-5 flex justify-between items-center
       bg-yellow-400 border-y border-black "
      >
        <div>
          <h1 className=" text-4xl sm:text-6xl max-w-xl font-serif">
            <span className="underline underline-offset-2 decoration-4">
              My Blog
            </span>{" "}
            is a place to write, read ,and connect with ME
          </h1>
          <h2>
            Discover stories, thinking, and expertise from ME.
          </h2>
        </div>

        <img
          className="object-contain hidden md:inline-flex h-32 lg:h-full"
          src="images/beard.png"
          alt="logo"
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 p-3 md:p-6 gap-3 md:gap-6">
        {posts.map((post) => (
          <Link key={post._id} href={`/post/${post.slug.current}`}>
            <div className="group shadow-md p-1 border-yellow-300 border-spacing-5 border cursor-pointer overflow-hidden">
              <Image
                height={150}
                width="200%"
                className="h-auto object-cover group-hover:scale-105 transition-all duration-200 ease-in-out rounded-sm"
                src={urlFor(post?.mainImage).url()}
                alt="image"
                loading="lazy"
                layout="responsive"
              />
              <div className="flex justify-between p-3 bg-white">
                <div>
                  <p className="font-bold capitalize text-lg">{post.title}</p>
                  <p className="text-gray-600 font-semibold text-sm ">
                    {post.description} by{" "}
                    <span className="underline underline-offset-2">
                      {post.author.name}
                    </span>
                  </p>
                </div>
                <img
                  className="h-12 w-12 rounded-full object-cover"
                  src={urlFor(post?.author.image).url()!}
                  alt=""
                />
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `*[_type == "post"]{
    _id,
    title,
    description,
    mainImage,
    slug,
    author-> {
      name,
      image
  },
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};
